/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package taqueria;

import Conexion.Conexion;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 1
 */
public class GestionarProducto extends javax.swing.JInternalFrame {
    private int id_Producto; 
    public GestionarProducto() {
        initComponents();
        this.setSize(new Dimension(600,400));
        this.setTitle("Gestionar Productos");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGP = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGDescp = new javax.swing.JTextField();
        txtGCantidad = new javax.swing.JTextField();
        txtGProveedor = new javax.swing.JTextField();
        txtGProducto = new javax.swing.JTextField();
        buttonEliminarP = new javax.swing.JButton();
        buttonActualizarP = new javax.swing.JButton();

        setBackground(new java.awt.Color(211, 207, 195));
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 0, -1, -1));

        tablaGP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaGP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Cantidad", "Proveedor"
            }
        ));
        jScrollPane1.setViewportView(tablaGP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 535, 144));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Proveedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(txtGDescp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 330, -1));
        getContentPane().add(txtGCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 330, -1));
        getContentPane().add(txtGProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 330, -1));
        getContentPane().add(txtGProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 330, -1));

        buttonEliminarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EliminarP.png"))); // NOI18N
        buttonEliminarP.setText("Eliminar");
        buttonEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarPActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 110, -1));

        buttonActualizarP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonActualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/configuraciones.png"))); // NOI18N
        buttonActualizarP.setText("Actualizar");
        buttonActualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarPActionPerformed(evt);
            }
        });
        getContentPane().add(buttonActualizarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarPActionPerformed

    private void buttonActualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonActualizarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonActualizarP;
    private javax.swing.JButton buttonEliminarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaGP;
    private javax.swing.JTextField txtGCantidad;
    private javax.swing.JTextField txtGDescp;
    private javax.swing.JTextField txtGProducto;
    private javax.swing.JTextField txtGProveedor;
    // End of variables declaration//GEN-END:variables
// Metodo para mostrar todas los datos del producto en la tabla
    private void TablaProdcutos(){
        Connection con= Conexion.conectar();  
        DefaultTableModel model= new DefaultTableModel();
        String sql = "select id_producto,nombre,descripcion,cantidad,proovedor";
        Statement st;
        
        try{
            st=con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            GestionarProducto.tablaGP= new JTable(model);
            GestionarProducto.jScrollPane1.setViewportView(GestionarProducto.tablaGP);
            model.addColumn("Id_Categoria");
            model.addColumn("Descripcion");
            model.addColumn("Categoria");
            model.addColumn("Proveedor");
            
            while(rs.next()){
                Object fila[] = new Object[3];
                for(int i=0;i<3;i++){
                    fila[i]=rs.getObject(i+1);
                }
                model.addRow(fila);
            }
            con.close();
        }catch(SQLException e){
            System.out.println("Error al llenar la tabla de productos");
        }
        
    }
}
