/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taqueria;

/**
 *
 * @author diego
 */
public class OpcionesMenu extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesMenu
     */
    private LoginTaqueria loginTaqueria;
    private Inventario inv;
    private Usuario usuarioLogged;
    
    public OpcionesMenu() {
        initComponents();
        /*
        if(usuarioLogged.getUserType() == "admin"){
            jLabel3.setVisible(false);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 33, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(576, 415));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opciones");

        jPanel2.setBackground(new java.awt.Color(108, 76, 60));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("Ir a");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ir a");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Ir a");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inventario");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manejo de sueldos");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestionar usuarios");

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar jornada");

        jButton5.setText("Ir a");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(71, 71, 71))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(29, 29, 29))
        );

<<<<<<< Updated upstream
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
=======
        menuSueldos.setBackground(new java.awt.Color(108, 76, 60));
        menuSueldos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sueldo.png"))); // NOI18N
        menuSueldos.setText("MANEJO DE SUELDOS");
        menuSueldos.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menuSueldos.setMinimumSize(new java.awt.Dimension(180, 80));
        menuSueldos.setPreferredSize(new java.awt.Dimension(210, 80));
        menuSueldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSueldosActionPerformed(evt);
            }
        });

        menuSueldo.setBackground(new java.awt.Color(211, 207, 195));
        menuSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sueldo.png"))); // NOI18N
        menuSueldo.setText("Sueldo");
        menuSueldo.setPreferredSize(new java.awt.Dimension(210, 50));
        menuSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSueldoActionPerformed(evt);
            }
        });
        menuSueldos.add(menuSueldo);

        menu.add(menuSueldos);

        menuJornada.setBackground(new java.awt.Color(108, 76, 60));
        menuJornada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Jornada.png"))); // NOI18N
        menuJornada.setText("REGISTRO DE JORNADA");
        menuJornada.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menuJornada.setMinimumSize(new java.awt.Dimension(180, 80));
        menuJornada.setPreferredSize(new java.awt.Dimension(210, 80));

        menuREntrada.setBackground(new java.awt.Color(211, 207, 195));
        menuREntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Entrada.png"))); // NOI18N
        menuREntrada.setText("Registrar jornada");
        menuREntrada.setPreferredSize(new java.awt.Dimension(210, 50));
        menuREntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuREntradaActionPerformed(evt);
            }
        });
        menuJornada.add(menuREntrada);

        menu.add(menuJornada);

        menuUsuario.setBackground(new java.awt.Color(211, 207, 195));
        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clientes.png"))); // NOI18N
        menuUsuario.setText("USUARIOS");
        menuUsuario.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menuUsuario.setMinimumSize(new java.awt.Dimension(180, 80));
        menuUsuario.setPreferredSize(new java.awt.Dimension(210, 50));

        menuRUsuario.setBackground(new java.awt.Color(211, 207, 195));
        menuRUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cliente.png"))); // NOI18N
        menuRUsuario.setText("Registrar usuario");
        menuRUsuario.setPreferredSize(new java.awt.Dimension(210, 50));
        menuRUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuRUsuario);

        menuMUsuario.setBackground(new java.awt.Color(211, 207, 195));
        menuMUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Modificar.png"))); // NOI18N
        menuMUsuario.setText("Gestionar usuarios");
        menuMUsuario.setPreferredSize(new java.awt.Dimension(210, 50));
        menuMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuMUsuario);

        menu.add(menuUsuario);

        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salir.png"))); // NOI18N
        menuSalir.setText("SALIR");
        menuSalir.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menuSalir.setMinimumSize(new java.awt.Dimension(180, 80));
        menuSalir.setPreferredSize(new java.awt.Dimension(210, 80));

        menuCerrarSesiion.setBackground(new java.awt.Color(211, 207, 195));
        menuCerrarSesiion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Exit.png"))); // NOI18N
        menuCerrarSesiion.setText("Cerrar sesion");
        menuCerrarSesiion.setPreferredSize(new java.awt.Dimension(210, 50));
        menuCerrarSesiion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesiionActionPerformed(evt);
            }
        });
        menuSalir.add(menuCerrarSesiion);

        menu.add(menuSalir);

        setJMenuBar(menu);
>>>>>>> Stashed changes

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("going to inventario");
        inv = new Inventario();
        inv.setOpcionesMenu(this);
        inv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loginTaqueria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

<<<<<<< Updated upstream
    public void setLoginTaqueria(LoginTaqueria loginTaqueria){
        this.loginTaqueria = loginTaqueria;
    }
    
    public void setUsuarioLogged(Usuario usuario){
        usuarioLogged = usuario;
=======
        JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente");

        // Redirigir al formulario de inicio de sesión
        
        LoginTaqueria formularioInicioSesion = new LoginTaqueria();
        formularioInicioSesion.setVisible(true);

        // Cerrar la ventana actual
        this.dispose();
    }//GEN-LAST:event_menuCerrarSesiionActionPerformed

    private void menuREntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuREntradaActionPerformed
       RegistrarJornada rj=new RegistrarJornada();
       jDesktopPane_menu.add(rj);
       rj.setVisible(true);
       rj.moveToFront();       
    }//GEN-LAST:event_menuREntradaActionPerformed

    private void menuSueldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSueldosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuSueldosActionPerformed

    private void menuSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSueldoActionPerformed
        // TODO add your handling code here:
        Sueldos s = new Sueldos();
        jDesktopPane_menu.add(s);
        s.setVisible(true);
        s.moveToFront();
    }//GEN-LAST:event_menuSueldoActionPerformed

    public void usuarioLoggedIn(Usuario usuario){
        usuarioLoggedIn = usuario;
        Ctrl_Usuario ctrlUsuario = new Ctrl_Usuario();
        ctrlUsuario.obtenerPuesto(usuarioLoggedIn);
        
        switch(usuarioLoggedIn.getPuestoEmpleado()){
            case "admin" -> {
                this.setTitle("TAQUERIA LA GLORIETA (admin)");
            }
            case "asador" -> {
                menuIProducto.setEnabled(false);
                menuMProducto.setEnabled(false);
                menuRVenta.setEnabled(false);
                jMenuItem1.setEnabled(false);
                jMenuItem5.setEnabled(false);
                menuSueldo.setEnabled(false);
                menuRUsuario.setEnabled(false);
                menuMUsuario.setEnabled(false);
                this.setTitle("TAQUERIA LA GLORIETA (asador)");
            }
            case "taquero" -> {
                menuIProducto.setEnabled(false);
                menuMProducto.setEnabled(false);
                menuRVenta.setEnabled(false);
                jMenuItem1.setEnabled(false);
                jMenuItem5.setEnabled(false);
                menuSueldo.setEnabled(false);
                menuRUsuario.setEnabled(false);
                menuMUsuario.setEnabled(false);
                this.setTitle("TAQUERIA LA GLORIETA (taquero)");
            }
            case "mesero" -> {
                menuIProducto.setEnabled(false);
                menuMProducto.setEnabled(false);
                menuRVenta.setEnabled(false);
                jMenuItem1.setEnabled(false);
                menuSueldo.setEnabled(false);
                menuRUsuario.setEnabled(false);
                menuMUsuario.setEnabled(false);
                this.setTitle("TAQUERIA LA GLORIETA (mesero)");
            }
            case "cajero" -> {
                menuIProducto.setEnabled(false);
                menuMProducto.setEnabled(false);
                menuRVenta.setEnabled(false);
                jMenuItem1.setEnabled(false);
                jMenuItem5.setEnabled(false);
                menuRUsuario.setEnabled(false);
                menuMUsuario.setEnabled(false);
                this.setTitle("TAQUERIA LA GLORIETA (cajero)");
            }
            default -> {
                menuIProducto.setEnabled(false);
                menuMProducto.setEnabled(false);
                menuRVenta.setEnabled(false);
                jMenuItem1.setEnabled(false);
                jMenuItem5.setEnabled(false);
                menuRUsuario.setEnabled(false);
                menuMUsuario.setEnabled(false);
                menuREntrada.setEnabled(false);
                menuSueldo.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Error: no se reconoció el puesto del empleado.");
                //System.out.println(usuario.getPuestoEmpleado());
            }
        }
>>>>>>> Stashed changes
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
