/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taqueria;

import java.awt.Dimension;


/**
 *
 * @author diego
 */
public class OpcionesMenu extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesMenu
     */
    private LoginTaqueria loginTaqueria;
    private Inventario inv;
    //private Usuario usuarioLogged;
    
    public OpcionesMenu() {
        initComponents();
        this.setSize(new Dimension (1200,700));
       // this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("TAQUERIA LA GLORIETA");
        
        /*
        if(usuarioLogged.getUserType() == "admin"){
            jLabel3.setVisible(false);
        }
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuIProducto = new javax.swing.JMenuItem();
        menuMProducto = new javax.swing.JMenuItem();
        menuEProducto = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuRVenta = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenu();
        menuSueldo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuREntrada = new javax.swing.JMenuItem();
        menuRSalida = new javax.swing.JMenuItem();
        menuRUsuario = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuMUsuario = new javax.swing.JMenuItem();
        menuEUsuario = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuCerrarSesiion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 33, 20));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(64, 33, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        jMenuBar1.setBackground(new java.awt.Color(108, 76, 60));
        jMenuBar1.setForeground(new java.awt.Color(108, 76, 60));

        jMenu2.setBackground(new java.awt.Color(108, 76, 60));
        jMenu2.setForeground(new java.awt.Color(108, 76, 60));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/inventario.png"))); // NOI18N
        jMenu2.setText("INVENTARIO");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jMenu2.setMinimumSize(new java.awt.Dimension(180, 80));
        jMenu2.setPreferredSize(new java.awt.Dimension(210, 50));

        menuIProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-producto.png"))); // NOI18N
        menuIProducto.setText("Ingresar producto");
        menuIProducto.setPreferredSize(new java.awt.Dimension(210, 50));
        jMenu2.add(menuIProducto);

        menuMProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        menuMProducto.setText("Modificar producto");
        menuMProducto.setPreferredSize(new java.awt.Dimension(210, 50));
        menuMProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMProductoActionPerformed(evt);
            }
        });
        jMenu2.add(menuMProducto);

        menuEProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/EliminarP.png"))); // NOI18N
        menuEProducto.setText("Eliminar producto");
        menuEProducto.setPreferredSize(new java.awt.Dimension(210, 50));
        jMenu2.add(menuEProducto);

        jMenuBar1.add(jMenu2);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ventas.png"))); // NOI18N
        jMenu6.setText("VENTAS");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jMenu6.setMinimumSize(new java.awt.Dimension(180, 80));
        jMenu6.setPreferredSize(new java.awt.Dimension(210, 80));

        menuRVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito.png"))); // NOI18N
        menuRVenta.setText("Registrar venta");
        menuRVenta.setPreferredSize(new java.awt.Dimension(210, 50));
        jMenu6.add(menuRVenta);

        jMenuBar1.add(jMenu6);

        menu.setBackground(new java.awt.Color(108, 76, 60));
        menu.setForeground(new java.awt.Color(108, 76, 60));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sueldo.png"))); // NOI18N
        menu.setText("MANEJO DE SUELDOS");
        menu.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menu.setMinimumSize(new java.awt.Dimension(180, 80));
        menu.setPreferredSize(new java.awt.Dimension(210, 80));

        menuSueldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sueldo.png"))); // NOI18N
        menuSueldo.setText("Sueldo");
        menuSueldo.setPreferredSize(new java.awt.Dimension(210, 50));
        menu.add(menuSueldo);

        jMenuBar1.add(menu);

        jMenu4.setBackground(new java.awt.Color(108, 76, 60));
        jMenu4.setForeground(new java.awt.Color(108, 76, 60));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Jornada.png"))); // NOI18N
        jMenu4.setText("REGISTRO DE JORNADA");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jMenu4.setMinimumSize(new java.awt.Dimension(180, 80));
        jMenu4.setPreferredSize(new java.awt.Dimension(210, 80));

        menuREntrada.setText("Registrar entrada");
        jMenu4.add(menuREntrada);

        menuRSalida.setText("Registrar salida");
        menuRSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRSalidaActionPerformed(evt);
            }
        });
        jMenu4.add(menuRSalida);

        jMenuBar1.add(jMenu4);

        menuRUsuario.setBackground(new java.awt.Color(108, 76, 60));
        menuRUsuario.setForeground(new java.awt.Color(108, 76, 60));
        menuRUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clientes.png"))); // NOI18N
        menuRUsuario.setText("USUARIOS");
        menuRUsuario.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        menuRUsuario.setMinimumSize(new java.awt.Dimension(180, 80));
        menuRUsuario.setPreferredSize(new java.awt.Dimension(210, 80));

        jMenuItem8.setText("Registrar usuario");
        menuRUsuario.add(jMenuItem8);

        menuMUsuario.setText("Modificar usuario");
        menuMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMUsuarioActionPerformed(evt);
            }
        });
        menuRUsuario.add(menuMUsuario);

        menuEUsuario.setText("Eliminar usauario");
        menuEUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEUsuarioActionPerformed(evt);
            }
        });
        menuRUsuario.add(menuEUsuario);

        jMenuBar1.add(menuRUsuario);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Salir.png"))); // NOI18N
        jMenu5.setText("SALIR");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jMenu5.setMinimumSize(new java.awt.Dimension(180, 80));
        jMenu5.setPreferredSize(new java.awt.Dimension(210, 80));

        menuCerrarSesiion.setText("Cerrar sesion");
        jMenu5.add(menuCerrarSesiion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMProductoActionPerformed

    private void menuMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMUsuarioActionPerformed

    private void menuEUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEUsuarioActionPerformed

    private void menuRSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRSalidaActionPerformed

    public void setLoginTaqueria(LoginTaqueria loginTaqueria){
        this.loginTaqueria = loginTaqueria;
    }
    
   // public void setUsuarioLogged(Usuario usuario){
        //usuarioLogged = usuario;
  //  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuCerrarSesiion;
    private javax.swing.JMenuItem menuEProducto;
    private javax.swing.JMenuItem menuEUsuario;
    private javax.swing.JMenuItem menuIProducto;
    private javax.swing.JMenuItem menuMProducto;
    private javax.swing.JMenuItem menuMUsuario;
    private javax.swing.JMenuItem menuREntrada;
    private javax.swing.JMenuItem menuRSalida;
    private javax.swing.JMenu menuRUsuario;
    private javax.swing.JMenuItem menuRVenta;
    private javax.swing.JMenuItem menuSueldo;
    // End of variables declaration//GEN-END:variables
}
